// Generated by gencpp from file ros_arduino_msgs/DigitalSensorSetDirection.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORSETDIRECTION_H
#define ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORSETDIRECTION_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/DigitalSensorSetDirectionRequest.h>
#include <ros_arduino_msgs/DigitalSensorSetDirectionResponse.h>


namespace ros_arduino_msgs
{

struct DigitalSensorSetDirection
{

typedef DigitalSensorSetDirectionRequest Request;
typedef DigitalSensorSetDirectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DigitalSensorSetDirection
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorSetDirection > {
  static const char* value()
  {
    return "8ed8b14a7df13f0c44543de998e53af4";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorSetDirection&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::DigitalSensorSetDirection > {
  static const char* value()
  {
    return "ros_arduino_msgs/DigitalSensorSetDirection";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorSetDirection&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest> should match 
// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorSetDirection > 
template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::DigitalSensorSetDirection >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorSetDirectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest> should match 
// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorSetDirection > 
template<>
struct DataType< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::DigitalSensorSetDirection >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorSetDirectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorSetDirectionResponse> should match 
// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalSensorSetDirection > 
template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorSetDirectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::DigitalSensorSetDirection >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorSetDirectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorSetDirectionResponse> should match 
// service_traits::DataType< ::ros_arduino_msgs::DigitalSensorSetDirection > 
template<>
struct DataType< ::ros_arduino_msgs::DigitalSensorSetDirectionResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::DigitalSensorSetDirection >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalSensorSetDirectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORSETDIRECTION_H
