// Generated by gencpp from file ros_arduino_msgs/DigitalSensorSetDirectionRequest.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORSETDIRECTIONREQUEST_H
#define ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORSETDIRECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_arduino_msgs
{
template <class ContainerAllocator>
struct DigitalSensorSetDirectionRequest_
{
  typedef DigitalSensorSetDirectionRequest_<ContainerAllocator> Type;

  DigitalSensorSetDirectionRequest_()
    : direction(false)  {
    }
  DigitalSensorSetDirectionRequest_(const ContainerAllocator& _alloc)
    : direction(false)  {
    }



   typedef uint8_t _direction_type;
  _direction_type direction;




  typedef boost::shared_ptr< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DigitalSensorSetDirectionRequest_

typedef ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<std::allocator<void> > DigitalSensorSetDirectionRequest;

typedef boost::shared_ptr< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest > DigitalSensorSetDirectionRequestPtr;
typedef boost::shared_ptr< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest const> DigitalSensorSetDirectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_arduino_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ros_arduino_msgs': ['/home/beauty/beauty_ws/src/beauty_arduino/ros_arduino_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ed8b14a7df13f0c44543de998e53af4";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ed8b14a7df13f0cULL;
  static const uint64_t static_value2 = 0x44543de998e53af4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_arduino_msgs/DigitalSensorSetDirectionRequest";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool direction\n\
";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DigitalSensorSetDirectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_arduino_msgs::DigitalSensorSetDirectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_DIGITALSENSORSETDIRECTIONREQUEST_H
